"""Builds src/content/guide.generated.ts from src/content/guide.en.md and guide.km.md.

Run after editing either file:  python scripts/build-guide.py
Needs the Python "markdown" package (pip install markdown).
"""
import io, json, re
import markdown

SRC = "src/content/"


def render(path, prefix):
    n = [0]

    def slug(_value, _sep):
        n[0] += 1
        return "%s%d" % (prefix, n[0])

    md = markdown.Markdown(extensions=["tables", "toc"], extension_configs={"toc": {"slugify": slug}})
    body = md.convert(io.open(path, encoding="utf8").read())
    title = re.search(r"<h1[^>]*>(.*?)</h1>", body, flags=re.S).group(1)
    body = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body, count=1, flags=re.S).replace("<hr />", "")
    body = body.replace("<table>", '<div class="guide-table"><table>').replace("</table>", "</table></div>")
    toc = [{"id": i, "title": re.sub(r"<[^>]+>", "", t)} for i, t in re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', body)]
    return {"title": title, "html": body, "toc": toc}


out = {"km": render(SRC + "guide.km.md", "k"), "en": render(SRC + "guide.en.md", "e")}
io.open(SRC + "guide.generated.ts", "w", encoding="utf8", newline="\n").write(
    "// Generated by scripts/build-guide.py from guide.en.md and guide.km.md. Do not edit by hand.\n"
    "export type GuideDoc = { title: string; html: string; toc: { id: string; title: string }[] }\n"
    "export const GUIDE: Record<\"km\" | \"en\", GuideDoc> = " + json.dumps(out, ensure_ascii=False, indent=1) + "\n"
)
print("ok")
